site_name: Blackstart
site_url: https://pezops.github.io/blackstart
site_description: Declarative and secure infrastructure bootstrapping.
site_author: Mike

repo_url: https://github.com/pezops/blackstart
edit_uri: blob/master/docs/

theme:
  logo: images/power-outline.svg
  name: material
  features:
    - navigation.indexes
    - navigation.path
    - navigation.top
    - toc.follow

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

nav:
  - Introduction: README.md
  - Getting Started: getting-started.md
  - User Guide:
      - user-guide/README.md
      - Deploy: user-guide/deploy.md
      - Configuration: user-guide/configuration.md
      - Workflows: user-guide/workflows.md
      - Eventual Consistency: user-guide/eventual-consistency.md
      - Secure Practices: user-guide/secure-practices.md
      - Modules: user-guide/modules/*
  - Developer Guide:
      - developer-guide/README.md
      - Modules: developer-guide/modules.md
      - Core Types: developer-guide/types.md
      - Building: developer-guide/building.md
      - Release Process: developer-guide/release.md
  - About:
      - about/README.md
      - Release Notes: https://github.com/pezops/blackstart/releases
      - License: https://github.com/pezops/blackstart/blob/main/LICENSE

extra_css:
  - 'css/extra.css'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      use_pygments: true
  - pymdownx.snippets

plugins:
  - search
  - literate-nav
#  - literate-nav:
#      implicit_index: true
