serviceAccount:
  create: true
  name: "blackstart"
  annotations: {}

image:
  registry: "ghcr.io"
  repository: "pezops/blackstart"
  tag: ""
  pullPolicy: IfNotPresent

controller:
  enabled: true
  maxParallelReconciliations: 4
  resyncInterval: "15s"
  queueWaitWarningThreshold: "30s"

cronJob:
  enabled: false
  schedule: "*/3 * * * *" # Run every 3 minutes
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 60
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

watchAllNamespaces: true

rbac:
  create: true
  rules:
    - apiGroups: ["blackstart.pezops.github.io"]
      resources: ["workflows"]
      verbs: ["get", "list", "watch", "update"]
    - apiGroups: ["blackstart.pezops.github.io"]
      resources: ["workflows/status"]
      verbs: ["update"]
    # This allows the kubernetes modules to manage configmaps and secrets
    - apiGroups: [""]
      resources: ["secrets", "configmaps"]
      verbs: ["create", "list", "get", "update"]
