serviceAccount:
  create: true
  name: "blackstart"
  annotations: {}
  gcpWorkloadIdentity:
    enabled: false # Enable GKE Workload Identity linking to a Google Cloud IAM service account.
    username: "" # Username portion of the Google service account email (before @).
    projectID: "" # Project ID of the Google service account email (before .iam.gserviceaccount.com).
  awsIRSA:
    enabled: false # Enable Amazon EKS IAM roles for service accounts (IRSA).
    roleARN: "" # AWS Identity and Access Management (IAM) role ARN to assign.
    stsRegionalEndpoints: false # Use regional AWS STS endpoints.

image:
  registry: "ghcr.io"
  repository: "pezops/blackstart"
  tag: ""
  pullPolicy: IfNotPresent

controller:
  enabled: true
  maxParallelReconciliations: 4
  resyncInterval: "15s"
  queueWaitWarningThreshold: "30s"

cronJob:
  enabled: false
  schedule: "*/3 * * * *" # Run every 3 minutes
  concurrencyPolicy: "Forbid"
  startingDeadlineSeconds: 60
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1

watchAllNamespaces: true

rbac:
  create: true
  rules:
    - apiGroups: ["blackstart.pezops.github.io"]
      resources: ["workflows"]
      verbs: ["get", "list", "watch", "update"]
    - apiGroups: ["blackstart.pezops.github.io"]
      resources: ["workflows/status"]
      verbs: ["update"]
    # This allows the kubernetes modules to manage configmaps and secrets
    - apiGroups: [""]
      resources: ["secrets", "configmaps"]
      verbs: ["create", "list", "get", "update"]
