name: Pages Deploy

on:
  workflow_run:
    workflows: ["Release"]
    types:
      - completed

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  context-debug:
    name: Debug Context
    runs-on: ubuntu-latest
    steps:
      - name: Show event context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "${GITHUB_CONTEXT}"

  build-docs:
    name: Build Documentation (from tag)
    runs-on: ubuntu-latest
    if:
      github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_sha  ==
      github.sha
    steps:
      - name: Checkout code at tag
        uses: actions/checkout@v5
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"
          cache-dependency-path: "docs/requirements.txt"

      - name: Install dependencies
        run: pip install -r docs/requirements.txt

      - name: Build MkDocs site
        run: mkdocs build --strict

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/

  publish-pages:
    name: Publish Documentation to GitHub Pages
    runs-on: ubuntu-latest
    needs: build-docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
