name: Release Drafter

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

concurrency:
  group: release-drafter
  cancel-in-progress: false

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: Update draft release
        uses: release-drafter/release-drafter@v7
